-- MySQL Script generated by MySQL Workbench
-- Fri Apr 17 02:01:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema casbin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema casbin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casbin` DEFAULT CHARACTER SET utf8 ;
USE `casbin` ;

-- -----------------------------------------------------
-- Table `casbin`.`casbin_rule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casbin`.`casbin_rule` ;

CREATE TABLE IF NOT EXISTS `casbin`.`casbin_rule` (
  `p_type` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `v0` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `v1` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `v2` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `v3` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `v4` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `v5` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  INDEX `IDX_casbin_rule_p_type` USING BTREE (`p_type`),
  INDEX `IDX_casbin_rule_v0` USING BTREE (`v0`),
  INDEX `IDX_casbin_rule_v1` USING BTREE (`v1`),
  INDEX `IDX_casbin_rule_v2` USING BTREE (`v2`),
  INDEX `IDX_casbin_rule_v3` USING BTREE (`v3`),
  INDEX `IDX_casbin_rule_v4` USING BTREE (`v4`),
  INDEX `IDX_casbin_rule_v5` USING BTREE (`v5`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `casbin`.`casbin_rule`
-- -----------------------------------------------------
START TRANSACTION;
USE `casbin`;
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'admin', '/*', '.*', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/image', 'POST', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/submitstatistic', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/alltags', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/contest/:id/problem/:problemid/solutions', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/contest', 'POST', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/contests', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/contest/:id', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/contest/:id/users', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/contest/:id/teams', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/series', 'POST', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/serieses', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/series/:id', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/series/:id/contests', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/problem', 'POST', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/problems', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/problem/:id', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/problem/:id/datas', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/problem/:id/data/:filename', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/download/problem/:id/data/:filename', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/solution/:id/judgestatus', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/problem/:id/judgestatus', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/team', 'POST', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/teams', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/allteams', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/team/:id', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/team/:id/users', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/generator/compete', 'POST', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/generator/user', 'POST', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/allcontests', 'GET', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `casbin`.`casbin_rule` (`p_type`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) VALUES ('p', 'secondaryadmin', '/api/admin/users', 'GET', DEFAULT, DEFAULT, DEFAULT);

COMMIT;

