-- MySQL Script generated by MySQL Workbench
-- Fri Jun 26 13:27:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oj` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `oj` ;

-- -----------------------------------------------------
-- Table `oj`.`compileinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`compileinfo` (
  `solution_id` INT(11) NOT NULL,
  `error` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  INDEX `solution_id_index` USING BTREE (`solution_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`config` (
  `item` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `value` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY USING BTREE (`item`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`contest` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `defunct` TINYINT(4) NOT NULL DEFAULT '0',
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `private` TINYINT(4) NOT NULL DEFAULT '0',
  `team_mode` TINYINT(4) NOT NULL DEFAULT '0',
  `langmask` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `user_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`contest_problem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`contest_problem` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contest_id` INT(11) NOT NULL,
  `problem_id` INT(11) NOT NULL,
  `num` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `contest_id_index` USING BTREE (`contest_id`),
  INDEX `problem_id_index` USING BTREE (`problem_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `oj`.`contest_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`contest_series` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contest_id` INT(11) NOT NULL,
  `series_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `contest_id_index` USING BTREE (`contest_id`),
  INDEX `series_id_index` USING BTREE (`series_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `oj`.`contest_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`contest_team` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contest_id` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `contest_id_index` USING BTREE (`contest_id`),
  INDEX `team_id_index` USING BTREE (`team_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `oj`.`contest_team_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`contest_team_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contest_id` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `contest_id_index` USING BTREE (`contest_id`),
  INDEX `team_id_index` USING BTREE (`team_id`),
  INDEX `user_id_index` USING BTREE (`user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `oj`.`contest_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`contest_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contest_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `contest_id_index` USING BTREE (`contest_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `oj`.`custominput`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`custominput` (
  `solution_id` INT(11) NOT NULL,
  `input_text` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  INDEX `solution_id_index` USING BTREE (`solution_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`issue` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `problem_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY USING BTREE (`id`),
  INDEX `user_id_index` USING BTREE (`user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`new`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`new` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `content` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `top` INT(11) NOT NULL DEFAULT '0',
  `defunct` TINYINT(4) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `title_UNIQUE` USING BTREE (`title`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`problem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`problem` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `level` TINYINT(4) NOT NULL DEFAULT '0',
  `input` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `output` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `sample_input` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `sample_output` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `spj` TINYINT(4) NULL DEFAULT NULL,
  `hint` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `defunct` TINYINT(4) NOT NULL DEFAULT '1',
  `time_limit` INT(11) NOT NULL DEFAULT '0',
  `memory_limit` INT(11) NOT NULL DEFAULT '0',
  `accepted` INT(11) NOT NULL DEFAULT '0',
  `submit` INT(11) NOT NULL DEFAULT '0',
  `solved` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `user_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`problem_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`problem_tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `problem_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `problem_id_index` USING BTREE (`problem_id`),
  INDEX `tag_id_index` USING BTREE (`tag_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `oj`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`reply` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `reply_user_id` INT(11) NOT NULL,
  `reply_id` INT(11) NOT NULL,
  `issue_id` INT(11) NOT NULL,
  `content` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '0',
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY USING BTREE (`id`),
  INDEX `user_id_index` USING BTREE (`user_id`),
  INDEX `topic_id_index` USING BTREE (`issue_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`resetpassword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`resetpassword` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `expired_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `user_id_UNIQUE` USING BTREE (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`runtimeinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`runtimeinfo` (
  `solution_id` INT(11) NOT NULL,
  `error` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  INDEX `solution_id_index` USING BTREE (`solution_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`series` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `defunct` TINYINT(4) NOT NULL DEFAULT '0',
  `team_mode` TINYINT(4) NOT NULL DEFAULT '0',
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `user_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`solution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`solution` (
  `solution_id` INT(11) NOT NULL AUTO_INCREMENT,
  `problem_id` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `contest_id` INT(11) NOT NULL DEFAULT '0',
  `num` TINYINT(4) NOT NULL DEFAULT '0',
  `time` INT(11) NOT NULL DEFAULT '0',
  `memory` INT(11) NOT NULL DEFAULT '0',
  `in_date` DATETIME NOT NULL,
  `result` SMALLINT(6) NOT NULL,
  `language` SMALLINT(6) NOT NULL,
  `ip` VARCHAR(48) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `judgetime` DATETIME NULL DEFAULT NULL,
  `valid` TINYINT(4) NOT NULL DEFAULT '1',
  `code_length` INT(11) NOT NULL,
  `pass_rate` DECIMAL(3,2) NOT NULL DEFAULT 0.00,
  `lint_error` INT(11) NOT NULL DEFAULT '0',
  `judger` VARCHAR(48) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`solution_id`),
  INDEX `problem_id_index` USING BTREE (`problem_id`),
  INDEX `user_id_index` USING BTREE (`user_id`),
  INDEX `team_id_index` USING BTREE (`team_id`),
  INDEX `contest_id_index` USING BTREE (`contest_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`source_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`source_code` (
  `solution_id` INT(11) NOT NULL,
  `source` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `public` TINYINT(4) NOT NULL DEFAULT '0',
  INDEX `solution_id_index` USING BTREE (`solution_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `name_UNIQUE` USING BTREE (`name`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`team` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
  `user_id` INT(11) NULL DEFAULT '0',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `oj`.`team_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`team_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `team_id_index` USING BTREE (`team_id`),
  INDEX `user_id_index` USING BTREE (`user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `oj`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oj`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(40) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `username` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nick` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `avatar` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `passsalt` VARCHAR(16) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `submit` INT(11) NOT NULL DEFAULT '0',
  `solved` INT(11) NOT NULL DEFAULT '0',
  `defunct` TINYINT(4) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_compete_user` TINYINT(4) NOT NULL DEFAULT '0',
  `role_id` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `username_UNIQUE` USING BTREE (`username`),
  UNIQUE INDEX `nick_UNIQUE` USING BTREE (`nick`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `oj`.`config`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`config` (`item`, `value`) VALUES ('enable_issue', 'true');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`role` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES (1, 'user', '', NOW(), NOW());
INSERT INTO `oj`.`role` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES (2, 'admin', '', NOW(), NOW());
INSERT INTO `oj`.`role` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES (3, 'secondaryadmin', '', NOW(), NOW());

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`user` (`id`, `email`, `username`, `nick`, `avatar`, `passsalt`, `password`, `submit`, `solved`, `defunct`, `created_at`, `updated_at`, `is_compete_user`, `role_id`) VALUES (1, '\'\'', 'admin', 'admin', 'static/images/default_avatar.png', 'abcdefghijklmnop', '72bd4f7ef86a8492eba63b96ee11d1f329fff8cc', 0, 0, 0, NOW(), NOW(), 0, 2);

COMMIT;

